const SAMPLE_TRADES = [
  {
    id: 1,
    date: "2025-01-05",
    symbol: "BTC",
    direction: "多",
    entryPrice: 42150,
    exitPrice: 44800,
    quantity: 0.5,
    fee: 22,
    pnl: 1303,
    strategy: "突破",
    emotion: "冷静",
    market: "趋势",
  },
  {
    id: 2,
    date: "2025-01-12",
    symbol: "ETH",
    direction: "多",
    entryPrice: 2280,
    exitPrice: 2150,
    quantity: 5,
    fee: 12,
    pnl: -662,
    strategy: "回调",
    emotion: "冲动",
    market: "震荡",
  },
  {
    id: 3,
    date: "2025-01-20",
    symbol: "SOL",
    direction: "多",
    entryPrice: 95,
    exitPrice: 118,
    quantity: 50,
    fee: 8,
    pnl: 1142,
    strategy: "突破",
    emotion: "冷静",
    market: "趋势",
  },
  {
    id: 4,
    date: "2025-02-03",
    symbol: "BTC",
    direction: "空",
    entryPrice: 46200,
    exitPrice: 44800,
    quantity: 0.3,
    fee: 18,
    pnl: 402,
    strategy: "回调",
    emotion: "冷静",
    market: "震荡",
  },
  {
    id: 5,
    date: "2025-02-10",
    symbol: "ARB",
    direction: "多",
    entryPrice: 1.85,
    exitPrice: 1.62,
    quantity: 3000,
    fee: 5,
    pnl: -695,
    strategy: "反弹",
    emotion: "犹豫",
    market: "震荡",
  },
  {
    id: 6,
    date: "2025-02-18",
    symbol: "ETH",
    direction: "多",
    entryPrice: 2650,
    exitPrice: 2920,
    quantity: 3,
    fee: 10,
    pnl: 800,
    strategy: "突破",
    emotion: "冷静",
    market: "趋势",
  },
  {
    id: 7,
    date: "2025-02-25",
    symbol: "TAO",
    direction: "空",
    entryPrice: 420,
    exitPrice: 385,
    quantity: 8,
    fee: 6,
    pnl: 274,
    strategy: "回调",
    emotion: "冷静",
    market: "趋势",
  },
  {
    id: 8,
    date: "2025-03-01",
    symbol: "SOL",
    direction: "多",
    entryPrice: 135,
    exitPrice: 128,
    quantity: 30,
    fee: 7,
    pnl: -217,
    strategy: "反弹",
    emotion: "冲动",
    market: "震荡",
  },
  {
    id: 9,
    date: "2025-03-08",
    symbol: "BTC",
    direction: "多",
    entryPrice: 51200,
    exitPrice: 54800,
    quantity: 0.4,
    fee: 25,
    pnl: 1415,
    strategy: "突破",
    emotion: "冷静",
    market: "趋势",
  },
  {
    id: 10,
    date: "2025-03-16",
    symbol: "TAO",
    direction: "空",
    entryPrice: 287,
    exitPrice: 279,
    quantity: 5,
    fee: 4,
    pnl: 36,
    strategy: "回调",
    emotion: "冷静",
    market: "震荡",
  },
  {
    id: 11,
    date: "2025-03-19",
    symbol: "ARB",
    direction: "多",
    entryPrice: 0.11,
    exitPrice: null,
    quantity: 10000,
    fee: 2,
    pnl: 0,
    strategy: "反弹",
    emotion: "冷静",
    market: "震荡",
  },
];

export default SAMPLE_TRADES;
