export const font = `'Instrument Sans', 'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif`;
export const mono = `'JetBrains Mono', 'SF Mono', 'Fira Code', monospace`;

export const colors = {
  bg: "#FAFAF9",
  surface: "#FFFFFF",
  border: "#E8E8E6",
  borderLight: "#F0F0EE",
  text: "#1A1A1A",
  textSecondary: "#8A8A86",
  textTertiary: "#B0B0AC",
  profit: "#16A34A",
  profitBg: "#F0FDF4",
  loss: "#DC2626",
  lossBg: "#FEF2F2",
  accent: "#1A1A1A",
  accentLight: "#F5F5F4",
  hover: "#F7F7F5",
  tag: "#EDEDE9",
};

export const S = {
  app: {
    display: "flex",
    minHeight: "100vh",
    fontFamily: font,
    background: colors.bg,
    color: colors.text,
  },
  sidebar: {
    width: 64,
    minWidth: 64,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 32,
    gap: 6,
    position: "fixed",
    top: 0,
    left: 0,
    height: "100vh",
    zIndex: 50,
  },
  navTab: (active) => ({
    width: 40,
    height: 40,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: active ? 600 : 400,
    color: active ? colors.text : colors.textTertiary,
    background: active ? colors.surface : "transparent",
    border: active ? `1px solid ${colors.border}` : "1px solid transparent",
    cursor: "pointer",
    fontFamily: font,
    letterSpacing: 0,
    transition: "all 0.25s ease",
    boxShadow: active ? "0 1px 3px rgba(0,0,0,0.04)" : "none",
  }),
  mainWrap: {
    flex: 1,
    marginLeft: 64,
    display: "flex",
    justifyContent: "center",
    overflow: "auto",
  },
  main: {
    width: "100%",
    maxWidth: 1200,
    padding: "44px 44px 56px",
    boxSizing: "border-box",
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: 700,
    letterSpacing: -0.6,
    marginBottom: 8,
  },
  pageSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 36,
    fontWeight: 400,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 20,
    marginBottom: 28,
  },
  statCard: {
    background: colors.surface,
    borderRadius: 14,
    padding: "24px 26px",
    border: `1px solid ${colors.border}`,
  },
  statLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  statValue: (c) => ({
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: -1,
    fontFamily: mono,
    color: c || colors.text,
  }),
  statSub: { fontSize: 12, color: colors.textSecondary, marginTop: 8 },
  card: {
    background: colors.surface,
    borderRadius: 14,
    border: `1px solid ${colors.border}`,
    marginBottom: 0,
  },
  cardHeader: {
    padding: "20px 26px",
    borderBottom: `1px solid ${colors.borderLight}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardTitle: { fontSize: 15, fontWeight: 600, letterSpacing: -0.2 },
  cardBody: { padding: 26 },
  table: { width: "100%", borderCollapse: "separate", borderSpacing: 0 },
  th: {
    textAlign: "left",
    padding: "10px 11px",
    fontSize: 11,
    fontWeight: 600,
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    borderBottom: `1px solid ${colors.border}`,
    background: colors.accentLight,
    whiteSpace: "nowrap",
  },
  td: {
    padding: "15px 11px",
    fontSize: 13,
    borderBottom: `1px solid ${colors.borderLight}`,
    fontFamily: font,
    whiteSpace: "nowrap",
  },
  pnl: (v) => ({
    color: v > 0 ? colors.profit : v < 0 ? colors.loss : colors.textSecondary,
    fontWeight: 600,
    fontFamily: mono,
  }),
  tag: (type) => {
    const map = {
      突破: "#1A1A1A",
      回调: "#6B5CE7",
      反弹: "#E08A2B",
    };
    const c = map[type] || "#888888";
    return {
      display: "inline-block",
      padding: "3px 10px",
      borderRadius: 6,
      fontSize: 11,
      fontWeight: 600,
      background: c + "12",
      color: c,
      letterSpacing: 0.2,
    };
  },
  dirTag: (d) => ({
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 600,
    background: d === "多" ? colors.profitBg : colors.lossBg,
    color: d === "多" ? colors.profit : colors.loss,
  }),
  btn: (variant) => ({
    padding: variant === "sm" ? "6px 12px" : "8px 16px",
    borderRadius: 8,
    fontSize: variant === "sm" ? 12 : 13,
    fontWeight: 500,
    border: `1px solid ${colors.border}`,
    background: colors.surface,
    color: colors.text,
    cursor: "pointer",
    fontFamily: font,
    letterSpacing: -0.1,
    transition: "all 0.15s",
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    outline: "none",
  }),
  btnPrimary: {
    padding: "8px 16px",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    border: "none",
    background: colors.text,
    color: "#fff",
    cursor: "pointer",
    fontFamily: font,
    letterSpacing: -0.1,
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    outline: "none",
  },
  input: {
    padding: "8px 12px",
    borderRadius: 8,
    fontSize: 13,
    border: `1px solid ${colors.border}`,
    background: colors.surface,
    fontFamily: font,
    outline: "none",
    width: "100%",
    color: colors.text,
    boxSizing: "border-box",
  },
  select: {
    padding: "8px 32px 8px 12px",
    borderRadius: 8,
    fontSize: 13,
    border: `1px solid ${colors.border}`,
    background: colors.surface,
    fontFamily: font,
    outline: "none",
    color: colors.text,
    cursor: "pointer",
    appearance: "auto",
  },
  textarea: {
    padding: "8px 12px",
    borderRadius: 8,
    fontSize: 13,
    border: `1px solid ${colors.border}`,
    background: colors.surface,
    fontFamily: font,
    outline: "none",
    width: "100%",
    color: colors.text,
    resize: "vertical",
    minHeight: 56,
    boxSizing: "border-box",
  },
  filterBar: {
    display: "flex",
    gap: 12,
    marginBottom: 24,
    flexWrap: "wrap",
    alignItems: "center",
  },
  emptyState: {
    textAlign: "center",
    padding: "60px 20px",
    color: colors.textSecondary,
  },
  modal: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.25)",
    backdropFilter: "blur(6px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 999,
  },
  modalContent: {
    background: colors.surface,
    borderRadius: 16,
    padding: 28,
    width: 520,
    overflow: "visible",
    boxShadow: "0 20px 60px rgba(0,0,0,0.1)",
  },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  formGroup: { display: "flex", flexDirection: "column", gap: 4 },
  formLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: colors.textSecondary,
    letterSpacing: 0.3,
  },
};
